-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "description" TEXT,
ALTER COLUMN "purchasePrice" DROP NOT NULL,
ALTER COLUMN "stock" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "salePrice" DROP NOT NULL,
ALTER COLUMN "tax" DROP NOT NULL;
